runMPI:
	mpiexec -np 4 ./Metodos/MPI/mpi_Final_version ./img/Original/image.png 630 1200

runOpenMP:
	./Metodos/OpenMP/OpenMP_version ./img/Original/image.png 4

runSecuencial:
	./Metodos/Secuencial/a.out ./img/Original/image.png